/* Script de creación de base de datos Firebird para Control de Horarios */

CREATE TABLE EMPLEADOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONO VARCHAR(20),
    CARGO VARCHAR(50),
    ACTIVO SMALLINT DEFAULT 1,
    FECHA_INGRESO DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USUARIOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    EMPLEADO_ID INTEGER NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROL VARCHAR(20) DEFAULT 'empleado',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(ID)
);

CREATE TABLE REGISTROS_HORARIO (
    ID INTEGER NOT NULL PRIMARY KEY,
    EMPLEADO_ID INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME,
    HORA_SALIDA TIME,
    OBSERVACIONES VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(ID)
);

CREATE TABLE HORARIOS_ASIGNADOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    EMPLEADO_ID INTEGER NOT NULL,
    DIA_SEMANA SMALLINT NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    ACTIVO SMALLINT DEFAULT 1,
    FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(ID)
);

/* Generadores para IDs autoincrementales */
CREATE GENERATOR GEN_EMPLEADOS_ID;
CREATE GENERATOR GEN_USUARIOS_ID;
CREATE GENERATOR GEN_REGISTROS_ID;
CREATE GENERATOR GEN_HORARIOS_ID;

/* Triggers para autoincrementar IDs */
CREATE TRIGGER EMPLEADOS_BI FOR EMPLEADOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_EMPLEADOS_ID, 1);
END;

CREATE TRIGGER USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_USUARIOS_ID, 1);
END;

CREATE TRIGGER REGISTROS_BI FOR REGISTROS_HORARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_REGISTROS_ID, 1);
END;

CREATE TRIGGER HORARIOS_BI FOR HORARIOS_ASIGNADOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_HORARIOS_ID, 1);
END;
